automobiles/autosite/automobiles/urls.py
from django.conf.urls import url
 
from automobiles import views
 
app_name = 'automobiles'
 
urlpatterns = [
 
    # /automobiles/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /motorcycles/
    url(r'^car/motorcycles/$', views.IndexView2.as_view(), name='index2'),
    # /carownerownscars/
    url(r'^car/personownscars/$', views.IndexView3.as_view(), name='index3'),
     # /carowners/
    url(r'^car/person/$', views.IndexView4.as_view(), name='index4'),
    # /carownerownscars/
    url(r'^car/personownsmotorcycles/$', views.IndexView5.as_view(), name='index5'),
    # /carownerownscars/
   # url(r'^car/index6/$', views.IndexView6.as_view(), name='index6'),
 
    # cars/car/entry
    url(r'^car/entry/$',views.CarEntry.as_view(),name='car-entry'),
    url(r'^car/motorcycles/entry/$',views.MotorcycleEntry.as_view(),name='motorcycle-entry'),
    url(r'^car/personownscars/entry/$',views.PersonOwnsCarEntry.as_view(),name='personownscar-entry'),
    url(r'^car/person/entry/$',views.PersonEntry.as_view(),name='person-entry'),
    url(r'^car/personownsmotorcycle/entry/$',views.PersonOwnsMotorcycleEntry.as_view(),name='personownsmotorcycle-entry'),
 
    # cars/car/2
    url(r'^car/(?P<pk>[0-9]+)/$', views.CarUpdate.as_view(), name='car-update'),
    url(r'^car/motorcycles/(?P<pk>[0-9]+)/$', views.MotorcycleUpdate.as_view(), name='motorcycle-update'),
    url(r'^car/personownscars/(?P<pk>[0-9]+)/$', views.PersonOwnsCarUpdate.as_view(), name='personownscar-update'),
    url(r'^car/person/(?P<pk>[0-9]+)/$', views.PersonUpdate.as_view(), name='person-update'),
    url(r'^car/personownsmotorcycles/(?P<pk>[0-9]+)/$', views.PersonOwnsMotorcycleUpdate.as_view(), name='personownsmotorcycle-update'),
 
    # cars/car/(?P<pk>[0-9]+)/delete
    #url(r'^car/(?P<pk>[0-9]+)/delete$', views.CarDelete.as_view(), name='car-delete'),
 
]

automobiles/autosite/autosite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
 
    url(r'^admin/', admin.site.urls),
    url(r'^automobiles/',include('automobiles.urls')),
    url(r'^motorcycles/',include('automobiles.urls')),
  
 
]

automobiles/autosite/automobiles/models.py
from django.db import models

class Person(models.Model):
     user_id = models.CharField(max_length=200)
     first_name = models.CharField(max_length=200) 
     last_name = models.CharField(max_length=200)
     email = models.CharField(max_length=200)

     def __str__(self):
         return '%s %s' % (self.first_name, self.last_name)

     def get_absolute_url(self):
         return u'/automobiles/car/person'


class Car(models.Model):
     car_id = models.CharField(max_length=200)
     year = models.IntegerField(default=0) 
     make = models.CharField(max_length=200)
     model = models.CharField(max_length=200)
     price = models.IntegerField(default=0) 

     def __str__(self):
         return '%s %s' % (self.make, self.model)

     def get_absolute_url(self):
         return u'/automobiles/'

class Motorcycle(models.Model):
     motorcycle_id = models.CharField(max_length=200)
     year = models.IntegerField(default=0) 
     make = models.CharField(max_length=200)
     model = models.CharField(max_length=200)
     price = models.IntegerField(default=0) 
    
     def get_absolute_url(self):
         return u'/automobiles/car/motorcycles'

     def __str__(self):
         return '%s %s' % (self.make, self.model)

#class CarOwner(models.Model):
  #   person = models.OneToOneField(Person, on_delete=models.CASCADE, primary_key= True,)

   #  def get_absolute_url(self):
  #       return u'/automobiles/car/carowners'

#class MotorcycleOwner(models.Model):
 #    person = models.OneToOneField(Person, on_delete=models.CASCADE, primary_key= True,)

class PersonOwnsCar(models.Model):
     Quantity = models.IntegerField(default=0)
     Person = models.ForeignKey(Person, on_delete=models.CASCADE)
     Car = models.ForeignKey(Car, on_delete=models.CASCADE)

     def get_absolute_url(self):
         return u'/automobiles/car/personownscars'

class PersonOwnsMotorcycle(models.Model):
     Quantity = models.IntegerField(default=0)
     Person = models.ForeignKey(Person, on_delete=models.CASCADE)
     Motorcycle = models.ForeignKey(Motorcycle, on_delete=models.CASCADE)

     def get_absolute_url(self):
         return u'/automobiles/car/personownsmotorcycles'

 

automobiles/autosite/automobiles/views.py
from django.shortcuts import render

from django.http import Http404

from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse

from .models import Car
from .models import Motorcycle
from .models import PersonOwnsCar
from .models import PersonOwnsMotorcycle
from .models import Person
from django.template import loader

from django.template.response import TemplateResponse
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
#from django.core.urlresolvers import reverse_lazy
 
# Create your views here.
from automobiles.models import Car
from automobiles.models import Motorcycle
from automobiles.models import PersonOwnsCar
from automobiles.models import PersonOwnsMotorcycle
from automobiles.models import Person

# view for the index page
class IndexView(generic.ListView):
    context_object_name = 'car_list'
     
    template_name = 'automobiles/index.html'

    def Index(request):
        car_list = Car.objects.all()
        return render(request, 'automobiles/index.html', locals())



    def get_queryset(self):
        return Car.objects.all()
       

# view for the car entry page
class CarEntry(CreateView):
    model = Car
    # the fields mentioned below become the entry rows in the generated form
    fields = ['car_id', 'year', 'make', 'model', 'price']
 
# view for the product update page
class CarUpdate(UpdateView):
    model = Car
    # the fields mentioned below become the entry rows in the update form
    fields = ['car_id', 'year', 'make', 'model', 'price']

# view for the index page
class IndexView2(generic.ListView):
    context_object_name = 'motorcycle_list'
    template_name = 'automobiles/index2.html'

    def Index2(request):
        motorcycle_list = Motorcycle.objects.all()
        return render(request, 'automobiles/index2.html', locals())

    def get_queryset(self):
        return Motorcycle.objects.all()

 
# view for the car entry page
class MotorcycleEntry(CreateView):
    model = Motorcycle
     #the fields mentioned below become the entry rows in the generated form
    fields = ['motorcycle_id', 'year', 'make', 'model', 'price']
 
# view for the product update page
class MotorcycleUpdate(UpdateView):
    model = Motorcycle
    # the fields mentioned below become the entry rows in the update form
    fields = ['motorcycle_id', 'year', 'make', 'model', 'price']



class IndexView3(generic.ListView):
    context_object_name = 'personownscar_list'
    template_name = 'automobiles/index3.html'

    def Index3(request):
        personownscar_list = PersonOwnsCar.objects.all()
        return render(request, 'automobiles/index3.html', locals())

    def get_queryset(self):
        return PersonOwnsCar.objects.all()

 
# view for the car entry page
class PersonOwnsCarEntry(CreateView):
    model = PersonOwnsCar
     #the fields mentioned below become the entry rows in the generated form
    fields = ['Quantity', 'Person', 'Car']
 
# view for the product update page
class PersonOwnsCarUpdate(UpdateView):
    model = PersonOwnsCar
 #   # the fields mentioned below become the entry rows in the update form
    fields = ['Quantity', 'Person', 'Car']



class IndexView4(generic.ListView):
    context_object_name = 'person_list'
    template_name = 'automobiles/index4.html'

    def Index4(request):
        person_list = Person.objects.all()
        return render(request, 'automobiles/index4.html', locals())

    def get_queryset(self):
        return Person.objects.all()

 
# view for the car entry page
class PersonEntry(CreateView):
    model = Person
   #  the fields mentioned below become the entry rows in the generated form
    fields = ['user_id', 'first_name', 'last_name', 'email']
 
 #view for the product update page
class PersonUpdate(UpdateView):
    model = Person
     #the fields mentioned below become the entry rows in the update form
    fields = ['user_id', 'first_name', 'last_name', 'email']

class IndexView5(generic.ListView):
    context_object_name = 'personownsmotorcycle_list'
    template_name = 'automobiles/index5.html'

    def Index5(request):
        personownsmotorcycle_list = PersonOwnsMotorcycle.objects.all()
        return render(request, 'automobiles/index5.html', locals())

    def get_queryset(self):
        return PersonOwnsMotorcycle.objects.all()

 
# view for the car entry page
class PersonOwnsMotorcycleEntry(CreateView):
    model = PersonOwnsMotorcycle
     #the fields mentioned below become the entry rows in the generated form
    fields = ['Quantity', 'Person', 'Motorcycle']
 
# view for the product update page
class PersonOwnsMotorcycleUpdate(UpdateView):
    model = PersonOwnsMotorcycle
 #   # the fields mentioned below become the entry rows in the update form
    fields = ['Quantity', 'Person', 'Motorcycle']





 

automobiles/autosite/automobiles/templates/automobiles/car_form.html
 <h3>Add a New Car</h3>
 
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'automobiles/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>

automobiles/autosite/automobiles/templates/automobiles/form-template.html
{% for field in form %}
    <div class="form-group">
        <div >
            <span class="text-danger la">{{ field.errors }}</span>
        </div>
        <label  >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

automobiles/autosite/automobiles/templates/automobiles/index.html
{# yonetim/templates/index.html #}
{% load render_table from django_tables2 %}
{% load static %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 
'ticket/static/css/screen.css' %}" />
    </head>
  

<p> click <a href="http://127.0.0.1:8000/automobiles/car/motorcycles/">here</a> for a list of motorcycles <br />
click <a href="http://127.0.0.1:8000/automobiles/car/personownscars/">here</a> for a list of Car Owners <br />
click <a href="http://127.0.0.1:8000/automobiles/car/personownsmotorcycles/">here</a> for a list of Motorcycle Owners <br />
click <a href="http://127.0.0.1:8000/automobiles/car/person/">here</a> for a list of People in the system <br />

 </p>

<h3> here is the car list </h3>

<body>
        {% render_table car_list %}
       
        
    </body>


 <form action="{% url 'automobiles:car-entry'  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Make a Car entry here</button>
        </form>


    {% for car in car_list %}
 
    <ul>
 
    <li>
        <h3> Car_ID:{{ car.car_id }}</h3>
        
           
           <form action="{% url 'automobiles:car-update' car.id  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Update</button>
        </form>
 
 
    </li>
 
 
    </ul>
 
{% endfor %}
 

automobiles/autosite/automobiles/templates/automobiles/index2.html
{# yonetim/templates/index2.html #}
{% load render_table from django_tables2 %}
{% load static %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 
'ticket/static/css/screen.css' %}" />
    </head>

<p> click <a href="http://127.0.0.1:8000/automobiles/">here</a> for a list of cars <br />
click <a href="http://127.0.0.1:8000/automobiles/car/personownscars/">here</a> for a list of Car Owners <br />
click <a href="http://127.0.0.1:8000/automobiles/car/personownsmotorcycles/">here</a> for a list of Motorcycle Owners <br />
click <a href="http://127.0.0.1:8000/automobiles/car/person/">here</a> for a list of People in the system <br />

 </p>

<h3> here is the motorcycle list </h3>

    <body>
        {% render_table motorcycle_list %}
    </body>


 <form action="{% url 'automobiles:motorcycle-entry'  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Make a Motorcycle entry here</button>
        </form>


    {% for motorcycle in motorcycle_list %}
 
    <ul>
 
    <li>
        <h3> Motorcycle_ID:{{ motorcycle.motorcycle_id }}</h3>
        
           
           <form action="{% url 'automobiles:motorcycle-update' motorcycle.id  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Update</button>
        </form>
 
 
    </li>
 
 
    </ul>
 
{% endfor %}
 



</html>


 

automobiles/autosite/automobiles/templates/automobiles/index3.html
{# yonetim/templates/index3.html #}
{% load render_table from django_tables2 %}
{% load static %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 
'ticket/static/css/screen.css' %}" />
    </head>

<p> click <a href="http://127.0.0.1:8000/automobiles/car/motorcycles/">here</a> for a list of motorcycles <br />
click <a href="http://127.0.0.1:8000/automobiles/">here</a> for a list of Cars <br />
click <a href="http://127.0.0.1:8000/automobiles/car/personownsmotorcycles/">here</a> for a list of Motorcycle Owners <br />
click <a href="http://127.0.0.1:8000/automobiles/car/person/">here</a> for a list of People in the system <br />

 </p>

<h3> here are all the car owners </h3>

    <body>
        {% render_table personownscar_list %}
    </body>


 <form action="{% url 'automobiles:personownscar-entry'  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Make a Car Owner entry here</button>
        </form>


    {% for personownscar in personownscar_list %}
 
    <ul>
 
    <li>
        <h3> Car Owner ID:{{ personownscar.id }}</h3>
        
           
           <form action="{% url 'automobiles:personownscar-update' personownscar.id  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Update</button>
        </form>
 
 
    </li>
 
 
    </ul>
 
{% endfor %}
 



</html>


 

automobiles/autosite/automobiles/templates/automobiles/index4.html
{# yonetim/templates/index4.html #}
{% load render_table from django_tables2 %}
{% load static %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 
'ticket/static/css/screen.css' %}" />
    </head>

<p> click <a href="http://127.0.0.1:8000/automobiles/car/motorcycles/">here</a> for a list of motorcycles <br />
click <a href="http://127.0.0.1:8000/automobiles/car/personownscars/">here</a> for a list of Car Owners <br />
click <a href="http://127.0.0.1:8000/automobiles/car/personownsmotorcycles/">here</a> for a list of Motorcycle Owners <br />
click <a href="http://127.0.0.1:8000/automobiles/">here</a> for a list of cars <br />

 </p>

<h3> here are all the people in our database </h3>

    <body>
        {% render_table person_list %}
    </body>


 <form action="{% url 'automobiles:person-entry'  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Create a Person entry here</button>
        </form>


    {% for person in person_list %}
 
    <ul>
 
    <li>
        <h3> Person_ID:{{ person.user_id }}</h3>
        
           
           <form action="{% url 'automobiles:person-update' person.id  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Update</button>
        </form>
 
 
    </li>
 
 
    </ul>
 
{% endfor %}
 



</html>


 

automobiles/autosite/automobiles/templates/automobiles/index5.html
{# yonetim/templates/index5.html #}
{% load render_table from django_tables2 %}
{% load static %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 
'ticket/static/css/screen.css' %}" />
    </head>

<p> click <a href="http://127.0.0.1:8000/automobiles/car/motorcycles/">here</a> for a list of motorcycles <br />
click <a href="http://127.0.0.1:8000/automobiles/car/personownscars/">here</a> for a list of Car Owners <br />
click <a href="http://127.0.0.1:8000/automobiles/">here</a> for a list of cars <br />
click <a href="http://127.0.0.1:8000/automobiles/car/person/">here</a> for a list of People in the system <br />

 </p>

<h3> here are all the motorcycle owners </h3>


    <body>
        {% render_table personownsmotorcycle_list %}
    </body>


 <form action="{% url 'automobiles:personownsmotorcycle-entry'  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Make a Motorcycle Owner entry here</button>
        </form>


    {% for personownsmotorcycle in personownsmotorcycle_list %}
 
    <ul>
 
    <li>
        <h3> Motorcycle Owner ID:{{ personownsmotorcycle.id }}</h3>
        
           
           <form action="{% url 'automobiles:personownsmotorcycle-update' personownsmotorcycle.id  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Update</button>
        </form>
 
 
    </li>
 
 
    </ul>
 
{% endfor %}
 



</html>


 

automobiles/autosite/automobiles/templates/automobiles/index6.html
<h3>Welcome to the Car Dealership Home page  for workers</h3>
 

automobiles/autosite/automobiles/templates/automobiles/motorcycle_form.html
 <h3>Add a New Motorcycle</h3>
 
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'automobiles/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>

automobiles/autosite/automobiles/templates/automobiles/person_form.html
 <h3>Add a New Person</h3>
 
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'automobiles/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>

automobiles/autosite/automobiles/templates/automobiles/personownscar_form.html
 <h3>Add New Cars to a new car Owner!</h3>
 
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'automobiles/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>

automobiles/autosite/automobiles/templates/automobiles/personownsmotorcycle_form.html
 <h3>Add New Motorcycles to a new motorcycle Owner!</h3>
 
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'automobiles/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>